### PR TITLE
Implement set ride status

### PR DESCRIPTION
**Pull request by IntelOrca**
This was a much more complicated function than I anticipated when coming to implement it. This is where all the checks are performed to ensure that the ride is compatible with its operating and vehicle settings. I would be grateful if there were some thorough tests. Checking all sorts of different rides, whether they open or not when they should be able to or not or otherwise display the correct problem message.

This also contains a large amount of refactoring related to the passing of map elements and x, y coordinates.

### CODE REVIEW

**Comment by adrian17** [comment]
Segfaults when trying to test a LIM launched coaster with any brake, like this:
image

**Comment by adrian17** [comment]
Build a ride without an entrance and try to test it -> you get moved to a wrong location:
image

**Comment by PFCKrutonium** [comment]
@adrian17 I think you missed the fact that you can't test Income - more than 1 bug in that screenshot.

**Comment by adrian17** [comment]
Build a simple Wooden Roller Coaster, try to test it -> no trains appear

image

**Comment by IntelOrca** [comment]
@adrian17 Thanks, I'll start working on these issues.

**Comment by IntelOrca** [comment]
@adrian17 Could you please see if 6911de9 has fixed your issues. Thanks.

**Comment by adrian17** [comment]
- brakes directly after station are not detected:

image

- Game hangs completely (no crashes, just hangs) when I test it when there are two block brakes near each other:

image

- Vehicles pass through tracks:

image

**Comment by adrian17** [comment]
Also hangs then trying to test a prebuilt wooden roller coaster "Driftwood" and possibly many others

**Comment by adrian17** [comment]
And that second bug with being moved to wrong location when there are no entrances is still happening.

**Comment by IntelOrca** [comment]
@adrian17 I assume you mean block brakes directly after station... normal brakes are allowed to be directly after station.

**Comment by adrian17** [comment]
Yes, these are block brakes.

**Comment by IntelOrca** [comment]
@adrian17 I think I have fixed those issues.

**Comment by adrian17** [comment]
For many designs it still hangs in this state:

image

**Comment by IntelOrca** [comment]
@adrian17 I tried driftwood, and it doesn't hang for me.

**Comment by adrian17** [comment]
A video with call stack: http://puu.sh/fGqvN/daf189de29.mp4

**Comment by IntelOrca** [comment]
@adrian17 Thanks.

**Comment by duncanspumpkin** [comment]
Ferris wheel gets stuck waiting on passengers. Same with trebuchet ride.

**Comment by IntelOrca** [comment]
What is a trebuchet ride?

**Comment by duncanspumpkin** [comment]
The spinny round arm one. There is one in sherwood forest level.

**Comment by IntelOrca** [comment]
I haven't got the expansion packs installed. What is the base ride type?

**Comment by duncanspumpkin** [comment]
http://rct.wikia.com/wiki/Top_Spin

**Comment by duncanspumpkin** [comment]
@adrian17 can you check the latest version. To see if there are any bugs.

**Comment by adrian17** [comment]
Build a ride without building any station (just placing a single non-station track is enough). Click test -> you get teleported to the corner of the map. RCT2 behavior: it doesn't teleport you at all when the ride doesn't have any stations.

**Comment by adrian17** [comment]
Now the exit detection has broken down.

image

**Comment by duncanspumpkin** [comment]
Sorry that's my fault I thought I switched back to a slightly different version of the entrance exit code. It's broken for entrance and exits connected to the same station track. I don't really like the code layout at present I plan to rewrite it.

**Comment by duncanspumpkin** [comment]
I've checked this function up until Line 3281 `sub_6B4D26`. I haven't come across anything that can trigger the ride suitability functions to return 0 yet. It would appear to mostly be working fine now but its hard to test every eventuality.

**Comment by IntelOrca** [comment]
Do you know what these functions do or are related to or what we could name them?
```
sub_6CAF80
sub_6B5952(int rideIndex)
sub_6B4D26
sub_6DD84C
sub_6DF4D4
```

**Comment by duncanspumpkin** [comment]
Not sure on the names without delving deeper into them.

**Comment by IntelOrca** [comment]
So are you up for merging this and dealing with problems on develop from there?

**Comment by duncanspumpkin** [comment]
Yeah I think so.

**Pull request merged**
