### PR TITLE
Custom sprites

### PR DESCRIPTION
**Pull request by IntelOrca**
I have added a currently very limited command line sprite editor to OpenRCT2. This allows you to export 8-bit PNGs from a sprite file and create and append any PNG file to a sprite file. The following was done to create g2.dat.

```
.\openrct2 sprite create g2.dat
.\openrct2 sprite append g2.dat logo.png
```

To get back the logo image to see if it has correctly imported it with the right colours, the following can be executed where 0 is sprite 0 in the g2.dat file.
```
.\openrct2 sprite export g2.dat 0 out_logo.png
```

So now this kind of works, I have added g2.dat with the logo. However I need help with the following things:
* The logo needs re-importing with better use of the RCT2 colour palette. It should be 256x256 (although this looks a bit big in the screenshot, so maybe smaller) and probably also use the flag. It would also be good if it actually said OpenRCT2 as well in front either on the same sprite or another.
* g2.dat currently does not copy to the build data folder when the solution is built. This needs to happen for both Visual Studio and cmake.
* Further testing to make sure there are no side effects or bugs.

Any improvement is welcome, particularly to the sprite editor - e.g. replacing a particular sprite in the file. One issue though is that the sprite file does not store the length of a sprite's data. This is fine for a BMP sprite (no transparency), but for an RLE sprite (transparency) there needs to be a function which calculates the length. Of course due to the way RLE sprites are stored, its possible for them to be interleaved with another sprite using the Y offsets table at the beginning.

Here is a screenshot of the title screen currently:
image

**Note:**
As it stands, to test this you will need to manually copy g2.dat from the ./data folder into the data folder where your built OpenRCT2 is.

g2 sprites can be used from the sprite index 324288 onwards. This number is just over the amount of spaced reserved for g1.dat - so I consider it safe until sprites are more organised. Once this PR is sorted, further custom sprites can be added for all our new features... like the random map generator tabs.

### CODE REVIEW

**Comment by JarnoVgr** [comment]
All I can say to this: nice

**Comment by Gymnasiast** [comment]
Indeed, nice work! It's also the first tool that really works on Linux.

Two things I noticed:
- The recolourable parts of a sprite are colored pink and black, although RCT2 GUI Editor, RCT2 Object Editor, Buggy's Ride Maker and possibly more tools used pink and lime. Is this a bug or should it work anyway?
- Currently, it cannot extract from csg1.dat (and probably csg1.1) from RCT1. Will eventually be necessary when importing RCT1 graphics (like missing land sides, land tops, trains, etc.)

**Comment by IntelOrca** [comment]
@Gymnasiast 
- I don't know enough to decide what is best, particularly where there also other palettes that remap colours.
- Yes, I doubt the format is too different so the code probably just needs tweaking.

**Comment by Gymnasiast** [comment]
The logo still suffers from flicker, and I think it's too big currently. 128x128 would work better.

**Comment by zsilencer** [comment]
why cant the g1 element just be overwritten?  are you planning on creating a newgrf kind of system as well?

**Comment by IntelOrca** [comment]
@zsilencer That would complicate things, particularly at the moment where we kind of what to keep the integrity of all the RCT2 files.

**Comment by trigger-death** [comment]
What method did you use for converting the image to the RCT2 palette? I use a basic difference method and mine is much sharper but has no smooth transitions like yours has:
</img>

**Comment by IntelOrca** [comment]
@trigger-death Someone posted it on the logo thread awhile ago. Yes, you will need something that can apply dithering if you want a smoother appearance.

**Pull request closed without merging**
