### PR TITLE
Fix bug in track design, EBPSAFE reworked

### PR DESCRIPTION
**Pull request by duncanspumpkin**
I've fixed a bug that is likely the cause of #606 and is the cause of #703. 
It was caused by not passing the parameter to the function. On windows by chance the value happened to be in the correct register. On otherOS for whatever reason the parameter was not in that register. 

In order to prevent this from happening again I've changed EBPSAFE to use a zeroed out version of CALLPROC_X that way EBPSAFE can only be used when the function has no arguments. This may, as a by product, produce a few bugs. I have already found one that occurred in the peep window. I've also removed EBPSAFE_X as it was not used anywhere.

### CODE REVIEW

**Comment by IntelOrca** [comment]
I suggest using 0xBBBBBBBB instead of 0 for EBPSAFE as its more glaringly obvious if a register is being used that we had suspected. Similar to how VS automatically initialises all memory to 0xCCCCCCCC in debug mode.

**Comment by duncanspumpkin** [comment]
Would that still trigger a dereference error. Is 0xBBBBBBBB guaranteed to be unaccessable memory?

**Comment by IntelOrca** [comment]
Chances are... yes :p

**Comment by duncanspumpkin** [comment]
Yeah I want to have the track design fixed first. Hopefully I can work out something tonight.

**Comment by duncanspumpkin** [comment]
It sounds like all of the bugs in the track design might be fixed so its almost ready for a merge. I think I might squash these commits together and make your change for normal register values (According to windows a 32bit programs invalid memory is anything above 0x80000000 so should be fine making it 0xBBBBBBBB, assuming no one messes with the 3GB switch) and then everything should be ready for a merge.

**Comment by duncanspumpkin** [comment]
Right that should be it squashed and ready for merging. This should hopefully close the following 4 issues. #606, #713, #612, #703

**Pull request merged**
