### PR TITLE
Decompiled window map overlay functions

### PR DESCRIPTION
**Pull request by adrian17**
There are still bugs remaining with `window_map_transform_to_map_coords`: the dots representing guests or staff should blink in blue (staff) or white (guests) when their respective list windows are open, but currently some guests and staff blink all the time even when no windows are open, and they blink in weird intervals; It happens also when I call the original code, so there is probably something wrong [here](https://github.com/IntelOrca/OpenRCT2/blob/develop/src/game.c#L253) and somewhere `peep->var_0C` is not set properly, but I can't find it :/

(the `goto`'s are temporary too, I wanted to leave them until the bug is fixed)

Also, the mentioned blinking is barely visible or not visible at all in windowed mode, I had to play with 800x600 in fullscreen to see them; that's another good reason for #775.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
https://github.com/IntelOrca/OpenRCT2/blob/d7212c1b1455a67119341cede0bc311e38f1324c/src/windows/staff_list.c#L318 That line is incorrect it should be |= (1<<2) not (1<<1). Can you switch everything that uses 0x9AC861 to use (1<<X) as it will be easier to read. Also suggest modifying https://github.com/IntelOrca/OpenRCT2/blob/develop/src/game.c#L253 to the following

```
RCT2_GLOBAL(0x009AC861, uint16) ^= (1 << 15);

// Handle guest map flashing
RCT2_GLOBAL(0x009AC861, uint16) &= ~(1 << 1);
if (RCT2_GLOBAL(0x009AC861, uint16) & (1 << 0)){
    RCT2_GLOBAL(0x009AC861, uint16) |= (1 << 1);
}
RCT2_GLOBAL(0x009AC861, uint16) &= ~(1 << 0);

// Handle staff map flashing
RCT2_GLOBAL(0x009AC861, uint16) &= ~(1 << 3);
if (RCT2_GLOBAL(0x009AC861, uint16) & (1 << 2)){
    RCT2_GLOBAL(0x009AC861, uint16) |= (1 << 3);
}
RCT2_GLOBAL(0x009AC861, uint16) &= ~(1 << 2);
```

I will check later tonight if there is anything messing up `peep->var_0C`.

**Comment by adrian17** [comment]
Okay, so what is happening is:

- guest list window sets (1<<0) every frame as long as it's open
- `game_update` clears (1<<0) and (1<<1), then sets (1<<1) if (1<<0) was set
- `window_map_paint_peep_overlay` reads (1<<1).

It seems to be just a way to just make sure that guest will flash only when guest list window is open, and staff will flash only when staff list window is open. Why isn't just checking `peep->var_0C` enough? I guess for some reason the flag was not always correctly set and this was a quick fix for this?

Anyway - it looks like everyone now flashes when it should, but the frequency still seems much lower than in RCT2.

**Comment by adrian17** [comment]
Oh, I get it. `peep->var_0C & 0x200` was unset for each guest/staff and set for selected ones by the windows on every frame, but it was never unset when the window closed so even when you load a save with no windows open, some peeps will have it set. 0x009AC861 is just a hacky fix to make them not flash. I think the proper fix would be to put

	FOR_ALL_GUESTS(spriteIndex, peep)
		peep->var_0C &= ~0x200;

in window_guest_list_close (which doesn't exist yet) and

	FOR_ALL_STAFF(spriteIndex, peep)
		peep->var_0C &= ~0x200;

in window_staff_list_close. I wonder why CS didn't do that.

**Comment by duncanspumpkin** [comment]
What would happen after a save/load? Thats the only case I can think of that would end up with it in a messed up state. Or does a load bring up the same windows that were closed with the filters still in place.

**Comment by adrian17** [comment]
> What would happen after a save/load? Thats the only case I can think of that would end up with it in a messed up state. 

Try this: remove [this check](https://github.com/IntelOrca/OpenRCT2/pull/801/files#diff-11c1847f6f46e178d571cab9519cc4e4R671) and [this check](https://github.com/IntelOrca/OpenRCT2/pull/801/files#diff-11c1847f6f46e178d571cab9519cc4e4R678) (these are the ones that check if corresponding guest/staff list windows are open)

- create empty park
- hire a handyman
- open a map window, you see him blink
- close the staff list window
- `peep->var_0C & 0x200` flag is still set, so he is still blinking. (He would stop blinking only if you opened staff list and changed the tab to something other than handyman - only then his flag is actually cleared).

That also transfers to the saves. When you open an existing or premade map without these checks, many seemingly random guests and staff will flash on the map.

**Comment by duncanspumpkin** [comment]
What happens in the original game?

**Pull request merged**
