### PR TITLE
Fix fullscreen issues

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by adrian17** [comment]
This fixed the two bugs I mentioned, but new ones appeared:

- probably connected to #708: when the config is set to fullscreen, the game still starts as window and immidetaly switches to fullscreen, so while loading there is a big white rectangle at the middle of the screen.
- When I'm in fullscreen and switch the resolution to the native one, the game also switches to fullscreen desktop mode. I'm not sure if that's intentional.
- Because of the above It's not possible to directly switch from fullscreen desktop to fullscreen; I have to switch to window, lower the resolution and then switch to fullscreen.
- when I switch to fullscreen desktop, it switches correctly but the dropdown displays Fullscreen and after reset the game also launches in fullscreen.

**Comment by IntelOrca** [comment]
not connected to #708. This hack is currently in place because resizing the window when fullscreen doesn't do anything. Changing to window and back to fullscreen is my temporary solution.

Try again to see if this latest commit fixes the fullscreen desktop issues.

**Comment by adrian17** [comment]
Okay, I meant that when the config is set to fullscreen, the game could directly start in that mode instead of starting as window and later switching to fullscreen.

Yes, this fixes the saving issues.

Now there's just one left, that in my native resolution (1400x1050) the "fullscreen" option always results in borderless fullscreen for some reason. I did some testing:

	SDL_CreateWindow("test", 0, 0, 1400, 1050, SDL_WINDOW_FULLSCREEN);

Results in normal fullscreen window, while

	SDL_CreateWindow("test", 0, 0, 800, 600, SDL_WINDOW_RESIZABLE);
	SDL_SetWindowSize(window, 1400, 1050);
	SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN);

Results in borderless fullscreen, even though I haven't mentioned `SDL_WINDOW_FULLSCREEN_DESKTOP` anywhere. Seems to be bug/intended behavior in SDL?

**Comment by IntelOrca** [comment]
Perhaps it is because the SDL_WINDOW_RESIZABLE flag needs to be removed?

**Comment by adrian17** [comment]
I don't see a way to remove this flag with the API. `SDL_SetWindowFullscreen` only modifies two window flags (0x00000001 and 0x00001000), while the WINDOW_RESIZABLE flag is 0x00000020. I can ask about this on the SDL forums later.

**Comment by adrian17** [comment]
For the record, I haven't gotten a response on the SDL forums yet.

**Comment by IntelOrca** [comment]
@adrian17 I wanted to merge this because it still fixes some of the problems you originally stated.

**Comment by adrian17** [comment]
Sure, no problem. Knowing SDL forums I won't figure the last one too quickly anyway.

**Comment by PFCKrutonium** [comment]
Have you considered asking on MDL or Guru3D? You might run into some people with relevant experience on those forums who can help.

**Pull request merged**
