### PR TITLE
EXPLODE!!!

### PR DESCRIPTION
**Pull request by LRFLEW**
Because why not

### CODE REVIEW

**Comment by IntelOrca** [comment]
What is calling climate_force_weather_smooth ?

**Comment by LRFLEW** [comment]
oh, whoops. Nothing anymore. That was back from my experiment with acid rain. It can be removed (however, I think it's useful).

**Comment by LRFLEW** [comment]
just realized I made a typo. Give me a minute to update the PR

**Comment by IntelOrca** [comment]
Save the weather stuff for another PR.

**Comment by LRFLEW** [comment]
Removed

**Comment by kevjoe** [comment]
This cheat is awesome.

**Pull request merged**
