### PR TITLE
Remove dashes after the colon at every language file

### PR DESCRIPTION
**Pull request by mrtnptrs**
As discussed at issue #521 This pull request removes all dashes behind the colons. Did I made any mistake, like removing ones, which shouldn't be removed? Or did I forgot one? If so, please comment and I'll fix it!

### CODE REVIEW

**Comment by Tinytimrob** [comment]
I am in support of the removal of the dash. It is a bit archaic nowadays. Also, I notice in the screenshot of Locomotion from #521, which the OpenRCT2 dialog is currently styled on, there is no dash.

locomotion

**Comment by mrtnptrs** [comment]
Can we then maybe finally merge this one? :) Nobody seems to like the dash.

**Comment by Gymnasiast** [comment]
How about keeping it in UK English, where it's valid, at least for now, and drop it in all others languages (including US English), where it isn't? The differences in opinion seems to be limited to UK English, so any discussion about just that could also be done at a later point. For such a simple PR it has been dragging along for quite a long time.

**Comment by Tinytimrob** [comment]
I think things should be kept consistent, so if the dash is dropped in all the other languages, it should be dropped in UK language file as well.

**Comment by Gymnasiast** [comment]
@Tinytimrob: The issue is not consistency, the issue is correctness. The dash is only valid in UK English, and incorrect in all others. Generally, consistency is important within a language file, but not between all language files. Every language has its conventions and quirks, and punctuation is part of that. For example, French uses spaces before exclamation and question marks, while these are incorrect in other languages. Making that consistent would mean making it incorrect in either French or in all other languages.
Since the only debatable language is UK English, I suggested dropping the dash for all other languages and have a separate discussion about just UK English.

**Comment by Wopian** [comment]
I've never seen any modern UK English site or book use the `:-`, it's also never taught in current education.

Edit: [This](http://bygonebureau.com/2010/01/20/the-secret-history-of-typography-in-the-oxford-english-dictionary/) might be of use.

**Comment by Tinytimrob** [comment]
@Gymnasiast: I see your point. I only partially agree with it.

If different languages have different punctuation conventions, then it makes sense to honour those conventions in the respective language files. But, if we have a "one option suits every language" choice, and none of the language files would be wrong with that choice, I think consistency across the different language files is equally important.

It seems the choices are between:
- Dash in all language files (already established as wrong)
- Dash only in the UK file
- No dashes in any file

Assuming we discount the first option, that just leaves the choice for the UK language file:
- To have a dash, and be different from the other language files
- Not to have a dash, and thus to be the same

While the dash is archaic, and not on current academic syllabus, it is still technically valid. But to *not* have the dash is *equally* valid. So the choice here is between two different but valid options, one which is consistent with the other language files and one which isn't. On that basis I feel it's best to go with what is consistent, rather than what isn't.

Some other points I think are relevant:
- At some point down the line there might be more strings added to OpenRCT2 which need to end with matching punctuation, and it is quite probable that if we use a different convention in the UK file, whoever adds the new strings might forget that or fail to notice it, and then you would end up with mismatches in the same file.
- In the future, if this project catches on and gets translated into a lot more languages, I would expect to see language inheritance (like with OpenTTD) where untranslated strings are pulled from the master language file (probably the US one), at which point the UK file can be stripped back to just the strings which differ from the US file (since the two languages are mostly the same). It would then be more effort to maintain the UK file to preserve the dashes.

About the only argument I can come up with to keep the dash is that it would match the original RCT2. But that seems to be a bit of a moot point, since one of the purposes of this project is to improve on the original game.

If you feel it is worthwhile, we could have an in-game option for toggling the dash on or off, but that seems a little excessive. I'm not sure that it is needed, or that anyone would bother to toggle it on if it was off by default. Such an option would also be irrelevant for some languages.

**Comment by Justasic** [comment]
I honestly agree with @Gymnasiast, although I am american and have not seen this punctuation I think it should be left up to the individual(s) who translated the game.

**Pull request merged**
