### PR TITLE
Fix peep

### LINKED ISSUE #760: Peeps seem to be unable to use benches
Save file attached:

https://mega.co.nz/#!mUEiCbKY!Tjjh0aFyuTu6oOBYpjg6Q7PIGHf-UQRy6pIYCRk6FzY

They just walk around, never sitting. Their legs must hurt ;)

As a side note, the game starts to get a bit laggy at around 1000 Peeps.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fixes #760 

I found a couple bugs in the peep code.
First there was a bug that caused peeps to not sit down unless they had a very specific combination of energy and nausea.
Second a small bug caused bins of one orientation to be missed.
Third there was a bug causing bins to never get filled. (Related to the tick count. I switched it to using random as i think it was just a simple way of doing random.)
Fourth an original bug causing bins to also never get filled. 
Fifth a bug that caused bins near by to get filled if a handyman empty one of them.

### CODE REVIEW

**Comment by mrtnptrs** [comment]
So, this also fixes the bug that handymans never empty bins in vanilla RCT2? :)

**Comment by mrtnptrs** [comment]
Nice to see the litter bins finally work in OpenRCT2, they never worked in the vanilla RCT2. Good job guys! :)

**Comment by adrian17** [comment]
Could be added as a bugfix [here](https://github.com/IntelOrca/OpenRCT2/blob/f52f75d303f72fb3665f0891121b5baf3814ee75/distribution/changelog.txt), then :D

**Comment by IntelOrca** [comment]
@adrian17 Done.

**Comment by PFCKrutonium** [comment]
>they never worked in the vanilla RCT2

Wait, what?!? How did I never notice this...

**Pull request merged**
