### PR TITLE
Small fixes for German translation

### PR DESCRIPTION
**Pull request by yayachiken**
Hi everyone,

the German translation of RollerCoaster 2 has always been kind of weird. As far as I remember there was even a community patch that changed some strings to the RCT1 variants.

I could not find this patch anymore, so I just went through the file on my own and picked out the most glaring mistranslations. 

These are:

* **Handwerker**: This is a literal translation of the word handyman. Unfortunately, Handwerker usually means tradesman or craftsman which could be confused with the mechanic. RCT1 called them "Hilfskraft" which means "temporary unskilled worker". I picked the term "Parkpfleger" which would translate to "park caretaker" and describes better what they do.

* **Beim Gehen**: Mistranslation of "Walking". This isn't even correct German grammar. RCT1 had "Geht" which just means "Walks" and sounds kind of weird but is at least correct. I picked "Läuft herum" which would translate to "wanders around" which I think fits most since this is the idle action.

Otherwise there have been only minor fixes. I could change a lot of minor things but these don't really bother that much imo.

### CODE REVIEW

**Comment by runelaenen** [comment]
Language changes should be done in the other language repo
https://github.com/OpenRCT2/Localisation

**Comment by Gymnasiast** [comment]
@runelaenen: Not when this PR was opened. Also, I'm not whether the PR author is still active. I looked at the changes and the author has provided a good reasoning, so we could merge in into the Localisation repo if he isn't active anymore.

**Comment by yayachiken** [comment]
Still watching everything, I can push to the other repo within this week, but not right now :)

**Comment by Gymnasiast** [comment]
Are discussing with @AllGoodNamesAreTaken, these fixes have now been merged into Localisation, so this can be closed.

**Comment by yayachiken** [comment]
Thanks for that.

Sorry on the lack of activity on my part, I just plain forgot.

**Pull request closed without merging**
