### PR TITLE
Refactor and Implementation of Remaining Object Paint Functions

### PR DESCRIPTION
**Pull request by duncanspumpkin**
It started as just a refactoring of object paint but then decided I might as well finish off all of the functions.
Requires more testing.

### CODE REVIEW

**Comment by IntelOrca** [comment]
More testing before merging?

**Comment by duncanspumpkin** [comment]
Yeah I'm not sure if its all working correctly there are quite a few edge cases.

**Comment by Gericom** [comment]
You can easily test it by going to the scenario creator. (It draws the preview and sometimes text for the object selection)

**Comment by duncanspumpkin** [comment]
Thats not the only code that uses object paint. When creating a new object list some different parts of the code is run. It can probably be merged today but there may be some small issues.

**Pull request merged**
