### PR TITLE
Added "zero clearance all" cheat

### PR DESCRIPTION
**Pull request by adrian17**

### CODE REVIEW

**Comment by IntelOrca** [comment]
I know this is the easiest way for a convenient zero clearance, but it essentially corrupts the whole map and can not be reverted. Many side effects can occur, for example drawing issues. It might need lots of warning around it.

**Comment by kevinburke** [comment]
Maybe would be better to check a flag before throwing a clearance-related
error?


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by adrian17** [comment]
It would be really nice to have some kind of universal Yes/Cancel window, like the staff fire prompt.

**Comment by Gymnasiast** [comment]
Isn't it possible to just disable clearance checks when using Zero Clearance mode, rather than actually setting _all_ clearances to zero? Or does it work that way already?

**Comment by IntelOrca** [comment]
@Gymnasiast We can only do that when all construction code is reversed.

**Comment by Gymnasiast** [comment]
@IntelOrca: I was fearing that.
Anyway, if the feature must be implemented now, rather than when all construction code is reversed: trainers for RCT2 (at least 8 cars per trainer) had the ability to restore clearances after using the zero clearances function (provided that both were used in the same session). Would that be possible?

**Comment by IntelOrca** [comment]
@Gymnasiast Yes, at least then players might not complain as much about their maps being corrupted.

**Comment by adrian17** [comment]
I will close it, based on the following:

- the cheat causes big graphical glitches:

image

- restoring the clearances would be harder than I thought - the player adding or removing map elements or the game reorganizing internal map element stack makes it hard to keep track of the elements we would need to restore,
- when the construction code is eventually reversed, implementing the cheat would be much easier, so the current approach would be temporary anyway.

**Pull request closed without merging**
