### PR TITLE
Download and extract title sequence in `make install`

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
https://travis-ci.org/janisozaur/OpenRCT2/jobs/185019287 says it should be correct, but I'd like someone to check it.

**Comment by Gymnasiast** [comment]
```
michael@Marcus-Aurelius:~/Programma's/Code/CLionProjects/OpenRCT2/build$ make install
[100%] Built target openrct2
Install the project...
-- Install configuration: "RELEASE"
[100%] Built target openrct2
Scanning dependencies of target g2
[100%] Generating g2.dat
usage: sprite build <spritefile> <resourcedir> [silent]
[100%] Built target g2
CMake Error at cmake_install.cmake:40 (file):
  file DOWNLOAD error: cannot create directory
  '/usr/local/share/openrct2/title' - Specify file by full path name and
  verify that you have directory creation and file write privileges.


Makefile:115: recept voor doel 'install' is mislukt
make: *** [install] Fout 1
```

**Comment by janisozaur** [comment]
Well, you don't have permissions to install it there. Why would you install it there, though, and not specify a package prefix?

**Comment by Gymnasiast** [comment]
Er, I never do `make install` anyway. I just copy the executable and run it.

**Comment by janisozaur** [comment]
Yes, that's the preferred way for me too, but in yuor snippet you show that `make install` fails gracefully with a message about missing permission, and not tested the newly added functionality. If you want to install it system-wide obtain required permissions or alternatively install it to a package prefix or build target `package`, but that depends more on your system.

Travis-made package looks correct to me, you can obtain from the link i posted.

**Pull request merged**
