### PR TITLE
Name more peep flags, import peeps on ride, import staff, import more peep fields

### PR DESCRIPTION
**Pull request by Gymnasiast**
This includes test code for importing litter, but it doesn't seem to work yet.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Could the changes that also apply to our current RCT2 code be made to develop?

**Comment by Gymnasiast** [comment]
I think the entire branch could be merged to develop.

**Comment by IntelOrca** [comment]
Have you checked if any scenarios crash?

**Comment by Gymnasiast** [comment]
Hm, I have one that does, but I'd have to test whether that happens in develop as well.

**Comment by Gymnasiast** [comment]
OK, I have managed to solve the crash - it was probably caused by peeps interacting with no longer existing vehicles.

**Pull request merged**
