### PR TITLE
Fix ride connected messages

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Noticed a small issue in the new map element code.

x, y coordinates swapped for these functions.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Is this purely on looking at the code difference or have you tested it?

**Comment by duncanspumpkin** [comment]
Tested it I was getting loads of ride not connected errors. Don't merge it just yet I think there might be another similar issue causing #718

**Comment by IntelOrca** [comment]
Oh... when x, y were the other way round I wasn't getting the messages when rides weren't connected.

**Comment by duncanspumpkin** [comment]
Hmm maybe something else is happening.

**Comment by duncanspumpkin** [comment]
Okay my commit is wrong. I will put up a correction shortly.

**Pull request merged**
