### PR TITLE
Lacked space(STR_0554)

### PR DESCRIPTION
**Pull request by miguelaquilas**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Can you also change it for English (UK), thanks.

**Comment by Gymnasiast** [comment]
Are you it wasn't spelled correctly? 'To freefall' is a verb which has no space between 'free' and 'fall', if I'm not mistaken. Also, I'm not sure if 'free falling back into the station' is grammatically correct.
What do the native speakers think?

**Comment by IntelOrca** [comment]
@Gymnasiast I think you're right in that "free fall" is a noun and "freefall" or "free-fall" is the verb equivalent.

**Comment by RollingStar** [comment]
[Free fall stats](https://books.google.com/ngrams/graph?content=freefall%2Cfreefalling%2Cfree+fall%2Cfree+falling%2C+free-fall%2C+free-falling&case_insensitive=on&year_start=1800&year_end=2008) from Google.

In American English there should not be a space between "free" and "falling". The hyphen seems to be the way most books address this.

**Comment by YamaArashi** [comment]
I checked several dictionaries and I think "free-falling" is the correct way to spell it in US and UK English.

For example, both of these spell the verb with a hyphen.
http://www.oxforddictionaries.com/us/definition/american_english/free-fall
http://www.oxforddictionaries.com/us/definition/english/free-fall

**Pull request closed without merging**
